---

- name: common
  src: git+ssh://git@github.com/anthcourtney/ansible-role-common.git
  version: master
  path: roles
- name: ntp
  src: git+ssh://git@github.com/anthcourtney/ansible-role-ntp.git
  version: master
  path: roles
- name: nginx
  src: git+ssh://git@github.com/anthcourtney/ansible-role-nginx.git
  version: master
  path: roles
- name: api
  src: git+ssh://git@github.com/anthcourtney/ansible-role-api.git
  version: master
  path: roles
- name: functional-tests
  src: git+ssh://git@github.com/anthcourtney/ansible-role-api-tests.git
  version: master
  path: roles
