---

- name: Setup environment
  hosts: all
  become: true
  serial: 1

  vars_files:
    - vars/main.yml

  pre_tasks:

  - name: Deregister instance from ELB
    local_action:
      module: ec2_elb
      instance_id: "{{ ansible_ec2_instance_id }}"
      state: absent 
    register: ec2_elbs

  roles:
    - common
    - ntp
    - nginx
    - api
    - { role: functional-tests, when: run_tests|default() | bool }

  post_tasks:

  - name: Register instance in ELB
    local_action:
      module: ec2_elb
      instance_id: "{{ ansible_ec2_instance_id }}"
      ec2_elbs: "{{ item }}"
      state: present
    with_items: "{{ ec2_elbs }}"	
