---

- name: Setup environment
  hosts: all
  become: true

  vars_files:
    - vars/main.yml

  roles:
    - common
    - ntp
    - nginx

  post_tasks:

  - name: Copy html content
    synchronize:
      src: "files/{{ nginx_root_dir }}/"
      dest: "{{ nginx_root_dir }}/"

- name: Include tests
  include: tests.yml
  when: run_tests is defined and run_tests
