---

- name: Setup environment
  hosts: all
  become: true

  vars_files:
    - vars/main.yml

  pre_tasks:

  - name: Check ansible version is suitable for this playbook
    assert:
      that: ansible_version.full | version_compare('2.1', '>=')
      msg: "Ansible version 2.1 or greater is required for this playbook"

  roles:
    - common
    - ntp
    - nginx
    - api

- name: Include tests
  include: tests.yml
  when: run_tests|default() | bool
