---

- name: Setup environment
  hosts: all
  become: true

  vars_files:
    - vars/main.yml

  pre_tasks:

  - name: Check ansible version is suitable for this playbook/role
    assert:
      that: ansible_version.full | version_compare('2.1', '>=')
      msg: "Ansible version 2.1 or greater is required for this playbook/role"

  roles:
    - common
    - ntp
    - nginx

  post_tasks:

  - name: Copy html content
    synchronize:
      src: "files/{{ nginx_root_dir }}/"
      dest: "{{ nginx_root_dir }}/"

- name: Include tests
  include: tests.yml
  when: run_tests is defined and run_tests
