---

- name: Run functional tests
  hosts: all
  become: true

  vars_files:
    - vars/main.yml

  tasks:

  - name: Access site via inventory_hostname
    uri:
      url: "http://{{ ansible_fqdn }}"
      status_code: 200
    register: uri_test
    tags:
      - functional-tests

  - name: Access secure area without authenticating
    uri:
      url: "http://{{ ansible_fqdn }}/api/users/anth"
      status_code: 401
    tags:
      - functional-tests

  - name: Access secure area with authentication
    uri:
      url: "http://{{ ansible_fqdn }}/api/users/anth"
      method: GET
      force_basic_auth: yes
      user: "{{ service_user }}"
      password: "{{ service_password }}"
    register: api_request
    tags:
      - functional-tests
    
  - name: Validate that api request response contains required information
    assert:
      that:
        - api_request.json.name is defined
        - api_request.json.username == 'anth'
        - api_request.json.email | search("@")
    tags:
      - functional-tests
