---

- name: Run functional tests
  hosts: all
  become: true

  vars_files:
    - vars/main.yml

  tasks:

# Start of block of tests
  - block:

    - name: Access site via inventory_hostname
      uri:
        url: "http://{{ ansible_fqdn }}"
        status_code: 200
      register: uri_test

    - name: Access secure area without authenticating
      uri:
        url: "http://{{ ansible_fqdn }}/api/users/anth"
        status_code: 401
      register: anon_api_request

    - name: Access secure area with authentication
      uri:
        url: "http://{{ ansible_fqdn }}/api/users/anth"
        method: GET
        force_basic_auth: yes
        user: "{{ service_user }}"
        password: "{{ service_password }}"
      register: auth_api_request

    ignore_errors: true  
    tags: 
      - functional-tests
# End of block of tests

  - name: Validate functional tests
    assert:
      that:
        - uri_test|success
        - anon_api_request|success
        - auth_api_request|success
        - auth_api_request.json.name is defined
        - auth_api_request.json.username == 'anth'
        - auth_api_request.json.email | search("@")
    tags:
      - functional-tests
